# Site settings
title: Jiboli - Portfolio
description: Portfolio of my illustrations
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: João Henrique Riboli

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/jiboli
gitlab_url: 
googleplus_url: 
telegram: https://t.me/jiboli  
instagram_url: https://www.instagram.com/jiboli/
linkedin_url: 
pinterest_url: https://br.pinterest.com/joaohenriquerib/
slack_url:
twitter_url: https://twitter.com/jiboli

# Build settings
markdown: kramdown
